/**
 * An enumeration for types of Nodes.
 *
 * @author hockeyhurd
 * @version 2022-11-01
 */

#pragma once

#ifndef CMM_ENUM_NODE_TYPE_H
#define CMM_ENUM_NODE_TYPE_H

namespace cmm
{
    enum class EnumNodeType
    {
        UNKNOWN = 0, ADDRESS_OF, ARG, CAST, COMPILATION_UNIT, BIN_OP, BLOCK, DEREF,
        FIELD_ACCESS, FUNCTION_CALL, FUNCTION_DECLARATION_STATEMENT, FUNCTION_DEFINITION_STATEMENT,
        EXPRESSION_STATEMENT, EXPRESSION, IF_ELSE_STATEMENT, PARAMETER, PAREN_EXPRESSION,
        LITTERAL, RETURN_STATEMENT, STRUCT_DEFINITION, STRUCT_FWD_DECLARATION, TRANSLATION_UNIT, UNARY_OP,
        VARIABLE, VARIABLE_DECLARATION_STATEMENT,
        WHILE_STATEMENT
    };
}

#endif //!CMM_ENUM_NODE_TYPE_H

