name: CMake

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'GithubActions'
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'main'
      - 'dev'


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          # TODO: Disable macos builds for now until new changes are resolved.
          #- {runs_on: macos-12, name: "macOS Clang", CC: clang, CXX: clang++, CFLAGS: "", CMAKE_BUILD_TYPE: "Debug"}
          - {runs_on: ubuntu-latest, name: "Clang 14 libc++", CC: clang-14, CXX: clang++-14, CFLAGS: "-stdlib=libc++", CMAKE_BUILD_TYPE: "Debug"}
          - {runs_on: ubuntu-latest, name: "Clang 14 libstdc++", CC: clang-14, CXX: clang++-14, CFLAGS: "-stdlib=libstdc++", CMAKE_BUILD_TYPE: "Debug"}
          - {runs_on: ubuntu-latest, name: "Clang 14 libstdc++ Release", CC: clang-14, CXX: clang++-14, CFLAGS: "-stdlib=libstdc++", CMAKE_BUILD_TYPE: "Release"}
          - {runs_on: ubuntu-latest, name: "GCC 12 Debug", CC: gcc-12, CXX: g++-12, CFLAGS: "", CMAKE_BUILD_TYPE: "Debug"}
          - {runs_on: ubuntu-latest, name: "GCC 12 Release", CC: gcc-12, CXX: g++-12, CFLAGS: "", CMAKE_BUILD_TYPE: "Release"}
          # TODO: Disable Windows builds for now until new changes are resolved.
          #- {runs_on: windows-latest, name: "MSVC", CFLAGS: "", CMAKE_BUILD_TYPE: "Debug"}
          #- {runs_on: windows-latest, name: "MSVC Release", CFLAGS: "", CMAKE_BUILD_TYPE: "Release"}
    runs-on: ${{ matrix.toolchain.runs_on }}
    env:
      # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
      CMAKE_BUILD_TYPE: ${{ matrix.toolchain.CMAKE_BUILD_TYPE }}
      CMAKE_C_COMPILER: ${{ matrix.toolchain.CC }}
      CMAKE_C_FLAGS: ${{ matrix.toolchain.CFLAGS }}
      CMAKE_CXX_COMPILER: ${{ matrix.toolchain.CXX }}
      CMAKE_CXX_FLAGS: ${{ matrix.toolchain.CFLAGS }}
      CMAKE_EXE_LINKER_FLAGS: ${{ matrix.toolchain.CFLAGS }}
      CMAKE_EXTRA_FLAGS: ${{ matrix.toolchain.CMAKE_FLAGS }}
      CMAKE_SHARED_LINKER_FLAGS: ${{ matrix.toolchain.CFLAGS }}

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Log versions
        run: cmake --version

      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cd ${{github.workspace}}/build && make all

      - name: Build Tests
        # Build your program with the given configuration
        run: cd ${{github.workspace}}/build && make tests

      - name: Test
        # working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: bash unitTest.sh
        shell: bash

